USE [LecturaMedidorDB]
GO

/****** Object:  Table [dbo].[TipoMedidor]    Script Date: 15-07-2022 14:55:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TipoMedidor](
	[IdTipo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](30) NULL,
 CONSTRAINT [PK_TipoMedidor] PRIMARY KEY CLUSTERED 
(
	[IdTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [LecturaMedidorDB]
GO

/****** Object:  Table [dbo].[Medidores]    Script Date: 15-07-2022 14:55:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Medidores](
	[IdMedidor] [int] NOT NULL,
	[IdTipoMedidor] [int] NOT NULL,
 CONSTRAINT [PK_Medidores] PRIMARY KEY CLUSTERED 
(
	[IdMedidor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Medidores]  WITH CHECK ADD  CONSTRAINT [FK_Medidores_Tipo] FOREIGN KEY([IdTipoMedidor])
REFERENCES [dbo].[TipoMedidor] ([IdTipo])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Medidores] CHECK CONSTRAINT [FK_Medidores_Tipo]
GO

USE [LecturaMedidorDB]
GO

/****** Object:  Table [dbo].[TipoMedidor]    Script Date: 15-07-2022 14:56:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TipoMedidor](
	[IdTipo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](30) NULL,
 CONSTRAINT [PK_TipoMedidor] PRIMARY KEY CLUSTERED 
(
	[IdTipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

