//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidorLecturaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        public int IdLectura { get; set; }
        public Nullable<int> Medidor { get; set; }
        public Nullable<decimal> Consumo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Medidore Medidore { get; set; }
    }
}
