//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidorLecturaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medidore()
        {
            this.Lecturas = new HashSet<Lectura>();
        }
    
        public int IdMedidor { get; set; }
        public int IdTipoMedidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lectura> Lecturas { get; set; }
        public virtual TipoMedidor TipoMedidor { get; set; }
    }
}
